config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/logout", to: "sessions#destroy"

  resources :carts, only: [:index, :destroy]
  resources :reviews, except: :update
  resources :product_orders
  resources :products
  resources :users
  resources :account_activations, only: :edit
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :login_checkouts
  resource :checkouts
  resource :orders, only: [:new, :update]
  resource :address, only: [:create, :update]
  resource :searchs

  namespace :admin do
    get "/login", to: "login#new"
    post "/login", to: "login#create"
    delete "/logout", to: "login#destroy"
    root "dashboard#index"
    get "dashboard/index"
    resources :products
    resources :categories
    resources :users
  end

end

app/views/layouts/admin/_footer.html.erb
<footer class="main-footer">
  <div class="pull-right hidden-xs">
    <b>Version</b> 2.3.2
  </div>
  <strong>
    Copyright &copy; 2014-2015
    <%= link_to "#", "Almsaeed Studio" %>.
  </strong> All rights reserved.
</footer>
<aside class="control-sidebar control-sidebar-dark">
  <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
    <li>
      <%= link_to "#control-sidebar-home-tab", "data-toggle" => "tab" do %>
        <i class="fa fa-home"></i>
      <% end %>
    </li>
    <li>
      <%= link_to "#control-sidebar-settings-tab", "data-toggle" => "tab" do %>
        <i class="fa fa-gears"></i>
      <% end %>
    </li>
  </ul>
  <div class="tab-content">
    <div class="tab-pane" id="control-sidebar-home-tab">
      <h3 class="control-sidebar-heading">Recent Activity</h3>
      <ul class="control-sidebar-menu">
        <li>
          <%= link_to "javascript::;" do %>
            <i class="menu-icon fa fa-birthday-cake bg-red"></i>
            <div class="menu-info">
              <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>
              <p>Will be 23 on April 24th</p>
            </div>
          <% end %>
        </li>
        <li>
          <%= link_to "javascript::;" do %>
            <i class="menu-icon fa fa-user bg-yellow"></i>
            <div class="menu-info">
              <h4 class="control-sidebar-subheading">Frodo Updated His Profile</h4>
              <p>New phone +1(800)555-1234</p>
            </div>
          <% end %>
        </li>
        <li>
          <%= link_to "javascript::;" do %>
            <i class="menu-icon fa fa-envelope-o bg-light-blue"></i>
            <div class="menu-info">
              <h4 class="control-sidebar-subheading">Nora Joined Mailing List</h4>
              <p>nora@example.com</p>
            </div>
          <% end %>
        </li>
        <li>
          <%= link_to "javascript::;" do %>
            <i class="menu-icon fa fa-file-code-o bg-green"></i>
            <div class="menu-info">
              <h4 class="control-sidebar-subheading">Cron Job 254 Executed</h4>
              <p>Execution time 5 seconds</p>
            </div>
          <% end %>
        </li>
      </ul>
      <h3 class="control-sidebar-heading">Tasks Progress</h3>
      <ul class="control-sidebar-menu">
        <li>
          <%= link_to "javascript::;" do %>
            <h4 class="control-sidebar-subheading">
              Custom Template Design
              <span class="label label-danger pull-right">70%</span>
            </h4>
            <div class="progress progress-xxs">
              <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
            </div>
          <% end %>
        </li>
        <li>
          <%= link_to "javascript::;" do %>
            <h4 class="control-sidebar-subheading">
              Update Resume
              <span class="label label-success pull-right">95%</span>
            </h4>
            <div class="progress progress-xxs">
              <div class="progress-bar progress-bar-success" style="width: 95%"></div>
            </div>
          <% end %>
        </li>
        <li>
          <%= link_to "javascript::;" do %>
            <h4 class="control-sidebar-subheading">
              Laravel Integration
              <span class="label label-warning pull-right">50%</span>
            </h4>

            <div class="progress progress-xxs">
              <div class="progress-bar progress-bar-warning" style="width: 50%"></div>
            </div>
          <% end %>
        </li>
        <li>
          <%= link_to "javascript::;" do %>
            <h4 class="control-sidebar-subheading">
              Back End Framework
              <span class="label label-primary pull-right">68%</span>
            </h4>

            <div class="progress progress-xxs">
              <div class="progress-bar progress-bar-primary" style="width: 68%"></div>
            </div>
          <% end %>
        </li>
      </ul>
    </div>
    <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>
    <div class="tab-pane" id="control-sidebar-settings-tab">
      <form method="post">
        <h3 class="control-sidebar-heading">General Settings</h3>
        <div class="form-group">
          <label class="control-sidebar-subheading">
            Report panel usage
            <input type="checkbox" class="pull-right" checked>
          </label>
          <p>
            Some information about this general settings option
          </p>
        </div>
        <div class="form-group">
          <label class="control-sidebar-subheading">
            Allow mail redirect
            <input type="checkbox" class="pull-right" checked>
          </label>
          <p>
            Other sets of options are available
          </p>
        </div>
        <div class="form-group">
          <label class="control-sidebar-subheading">
            Expose author name in posts
            <input type="checkbox" class="pull-right" checked>
          </label>
          <p>
            Allow the user to show his name in blog posts
          </p>
        </div>
        <h3 class="control-sidebar-heading">Chat Settings</h3>
        <div class="form-group">
          <label class="control-sidebar-subheading">
            Show me as online
            <input type="checkbox" class="pull-right" checked>
          </label>
        </div>
        <div class="form-group">
          <label class="control-sidebar-subheading">
            Turn off notifications
            <input type="checkbox" class="pull-right">
          </label>
        </div>
        <div class="form-group">
          <label class="control-sidebar-subheading">
            Delete chat history
            <%= link_to "javascript::;", class: "text-red pull-right" do %>
            < i class="fa fa-trash-o"></i>
            <% end %>
          </label>
        </div>
      </form>
    </div>
  </div>
</aside>
<div class="control-sidebar-bg"></div>

app/views/layouts/admin/_header.html.erb
<header class="main-header">
  <%= link_to "#", class: "logo" do %>
    <span class="logo-mini">
      <b>A</b>LT
    </span>
    <span class="logo-lg">
      <b>Vina</b>COOK
    </span>
  <% end %>
  <nav class="navbar navbar-static-top" role="navigation">
    <%= link_to "#", class: "sidebar-toggle", "data-toggle" => "offcanvas", "role" => "button" do %>
      <span class="sr-only">Toggle navigation</span>
    <% end %>
    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <li class="dropdown messages-menu">
          <%= link_to "#", class: "dropdown-toggle", "data-toggle" => "dropdown" do %>
            <i class="fa fa-envelope-o"></i>
            <span class="label label-success">4</span>
          <% end %>
          <ul class="dropdown-menu">
            <li class="header">You have 4 messages</li>
            <li>
              <ul class="menu">
                <li>
                  <%= link_to "#" do %>
                    <div class="pull-left">
                      <%= image_tag "admin/user2-160x160.jpg", class: "img-circle" %>
                    </div>
                    <h4>
                      Support Team
                      <small>
                        <i class="fa fa-clock-o"></i> 5 mins
                      </small>
                    </h4>
                    <p>Why not buy a new awesome theme?</p>
                  <% end %>
                </li>
                <li>
                  <%= link_to "#" do %>
                    <div class="pull-left">
                      <%= image_tag "admin/user3-128x128.jpg", class: "img-circle" %>
                    </div>
                    <h4>
                      AdminLTE Design Team
                      <small>
                        <i class="fa fa-clock-o"></i> 2 hours
                      </small>
                    </h4>
                    <p>Why not buy a new awesome theme?</p>
                  <% end %>
                </li>
                <li>
                  <%= link_to "#" do %>
                    <div class="pull-left">
                      <%= image_tag "admin/user4-128x128.jpg", class: "img-circle" %>
                    </div>
                    <h4>
                      Developers
                      <small>
                        <i class="fa fa-clock-o"></i> Today
                      </small>
                    </h4>
                    <p>Why not buy a new awesome theme?</p>
                  <% end %>
                </li>
                <li>
                  <%= link_to "#" do %>
                    <div class="pull-left">
                      <%= image_tag "admin/user3-128x128.jpg", class: "img-circle" %>
                    </div>
                    <h4>
                      Sales Department
                      <small>
                        <i class="fa fa-clock-o"></i> Yesterday
                      </small>
                    </h4>
                    <p>Why not buy a new awesome theme?</p>
                  <% end %>
                </li>
                <li>
                  <%= link_to "#" do %>
                    <div class="pull-left">
                      <%= image_tag "admin/user4-128x128.jpg", class: "img-circle" %>
                    </div>
                    <h4>
                      Reviewers
                      <small>
                        <i class="fa fa-clock-o"></i> 2 days
                      </small>
                    </h4>
                    <p>Why not buy a new awesome theme?</p>
                  <% end %>
                </li>
              </ul>
            </li>
            <li class="footer">
              <%= link_to "See All Messages", "#" %>
            </li>
          </ul>
        </li>
        <li class="dropdown notifications-menu">
          <%= link_to "#", class: "dropdown-toggle", "data-toggle" => "dropdown" do %>
            <i class="fa fa-bell-o"></i>
            <span class="label label-warning">10</span>
          <% end %>
          <ul class="dropdown-menu">
            <li class="header">You have 10 notifications</li>
            <li>
              <ul class="menu">
                <li>
                  <%= link_to "#" do %>
                    <i class="fa fa-users text-aqua"></i> 5 new members joined today
                  <% end %>
                </li>
                <li>
                  <%= link_to "#" do %>
                    <i class="fa fa-warning text-yellow"></i> Very long description here that may not fit into the
                    page and may cause design problems
                  <% end %>
                </li>
                <li>
                  <%= link_to "#" do %>
                    <i class="fa fa-users text-red"></i> 5 new members joined
                  <% end %>
                </li>
                <li>
                  <%= link_to "#" do %>
                    <i class="fa fa-shopping-cart text-green"></i> 25 sales made
                  <% end %>
                </li>
                <li>
                  <%= link_to "#" do %>
                    <i class="fa fa-user text-red"></i> You changed your username
                  <% end %>
                </li>
              </ul>
            </li>
            <li class="footer">
              <%= link_to "View all", "#" %>
            </li>
          </ul>
        </li>
        <li class="dropdown tasks-menu">
          <%= link_to "#", class: "dropdown-toggle", "data-toggle" => "dropdown" do %>
            <i class="fa fa-flag-o"></i>
            <span class="label label-danger">9</span>
          <% end %>
          <ul class="dropdown-menu">
            <li class="header">You have 9 tasks</li>
            <li>
              <ul class="menu">
                <li>
                  <%= link_to "#" do %>
                    <h3>
                      Design some buttons
                      <small class="pull-right">20%</small>
                    </h3>
                    <div class="progress xs">
                      <div class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                        <span class="sr-only">20% Complete</span>
                      </div>
                    </div>
                  <% end %>
                </li>
                <li>
                  <%= link_to "#" do %>
                    <h3>
                      Create a nice theme
                      <small class="pull-right">40%</small>
                    </h3>
                    <div class="progress xs">
                      <div class="progress-bar progress-bar-green" style="width: 40%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                        <span class="sr-only">40% Complete</span>
                      </div>
                    </div>
                  <% end %>
                </li>
                <li>
                  <%= link_to "#" do %>
                    <h3>
                      Some task I need to do
                      <small class="pull-right">60%</small>
                    </h3>
                    <div class="progress xs">
                      <div class="progress-bar progress-bar-red" style="width: 60%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                        <span class="sr-only">60% Complete</span>
                      </div>
                    </div>
                  <% end %>
                </li>
                <li>
                  <%= link_to "#" do %>
                    <h3>
                      Make beautiful transitions
                      <small class="pull-right">80%</small>
                    </h3>
                    <div class="progress xs">
                      <div class="progress-bar progress-bar-yellow" style="width: 80%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                        <span class="sr-only">80% Complete</span>
                      </div>
                    </div>
                  <% end %>
                </li>
              </ul>
            </li>
            <li class="footer">
              <%= link_to admin_root_path, "View all tasks" %>
            </li>
          </ul>
        </li>
        <li class="dropdown user user-menu">
          <%= link_to "#", class: "dropdown-toggle", "data-toggle" => "dropdown" do %>
            <span class="hidden-xs">Alexander Pierce</span>
          <% end %>
          <ul class="dropdown-menu">
            <li class="user-header">
              <%= image_tag "admin/user2-160x160.jpg", class: "img-circle" %>
              <p>
                Alexander Pierce - Web Developer
                <small>Member since Nov. 2012</small>
              </p>
            </li>
            <li class="user-body">
              <div class="row">
                <div class="col-xs-4 text-center">
                  <%= link_to "Followers", "#" %>
                </div>
                <div class="col-xs-4 text-center">
                  <%= link_to "Sales", "#" %>
                </div>
                <div class="col-xs-4 text-center">
                  <%= link_to "Friends", "#" %>
                </div>
              </div>
            </li>
            <li class="user-footer">
              <div class="pull-left">
                <%= link_to "Profile", "", class: "btn btn-default btn-flat" %>
              </div>
              <div class="pull-right">
                <%= link_to "Đăng xuất", admin_logout_path, method: :delete,class: "btn btn-default btn-flat" %>
                <%= link_to "Home", "", class: "btn btn-default btn-flat" %>
              </div>
            </li>
          </ul>
        </li>
        <li>
        <%= link_to "", "data-toggle" => "control-sidebar" do %>
            <i class="fa fa-gears"></i>
          <% end %>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/admin/_sidebar.html.erb
 <aside class="main-sidebar">
  <section class="sidebar">
    <div class="user-panel">
      <div class="pull-left image">
        <%= image_tag "admin/user2-160x160.jpg", class: "img-circle" %>
      </div>
      <div class="pull-left info">
        <p>Alexander Pierce</p>
        <%= link_to "#" do %>
          <i class="fa fa-circle text-success"></i> Online
        <% end %>
      </div>
    </div>
    <form action="#" method="get" class="sidebar-form">
      <div class="input-group">
        <input type="text" name="q" class="form-control" placeholder="Search...">
        <span class="input-group-btn">
          <button type="submit" name="search" id="search-btn" class="btn btn-flat">
            <i class="fa fa-search"></i>
          </button>
        </span>
      </div>
    </form>
    <ul class="sidebar-menu">
      <li class="header">MAIN NAVIGATION</li>
      <li class="treeview-dashboard">
        <%= link_to admin_root_path do %>
          <i class="fa fa-dashboard"></i>
          <span>Dashboard</span>
        <% end %>
      </li>
      <li class="treeview">
        <%= link_to "#" do %>
          <i class="fa fa-shopping-cart" aria-hidden="true"></i>
          <span>Sản phẩm</span>
          <i class="fa fa-angle-left pull-right"></i>
        <% end %>
        <ul class="treeview-menu">
          <li>
            <%=link_to "Sản phẩm", admin_products_path  %>
          </li>
          <li>
            <%=link_to "Tạo mới sản phẩm", new_admin_product_path %>
          </li>
        </ul>
      </li>
      <li class="treeview">
        <%= link_to "#" do %>
          <i class="fa fa-laptop"></i>
          <span>Danh mục</span>
          <i class="fa fa-angle-left pull-right"></i>
        <% end %>
        <ul class="treeview-menu">
          <li>
            <%= link_to "Tất cả chuyên mục", admin_categories_path %>
          </li>
          <li>
            <%= link_to "Tạo mới", new_admin_category_path %>
          </li>
        </ul>
      </li>
      <li class="treeview">
        <%= link_to "#" do %>
          <i class="fa fa-edit"></i>
          <span>Order</span>
          <i class="fa fa-angle-left pull-right"></i>
        <% end %>
        <ul class="treeview-menu">
          <li>
            <%= link_to "#" do %>
              Info Order
            <% end %>
          </li>
        </ul>
      </li>
      <li class="treeview">
        <%= link_to "#" do %>
          <i class="fa fa-user" aria-hidden="true"></i> <span>Quản lý người dùng</span>
          <i class="fa fa-angle-left pull-right"></i>
        <% end %>
        <ul class="treeview-menu">
          <li>
            <%= link_to admin_users_path do %>
              <i class="fa fa-circle-o"></i> Tất cả người dùng
            <% end %>
          </li>
          <li>
            <%= link_to new_admin_user_path do %>
              <i class="fa fa-circle-o"></i> Tạo mới người dùng
            <% end %>
          </li>
        </ul>
      </li>
      <li>
        <%= link_to "#" do %>
          <i class="fa fa-calendar"></i>
          <span>Calendar</span>
          <small class="label pull-right bg-red">3</small>
        <% end %>
      </li>
      <li>
        <%= link_to "#" do %>
          <i class="fa fa-envelope"></i>
          <span>Mailbox</span>
          <small class="label pull-right bg-yellow">12</small>
        <% end %>
      </li>
      <li class="treeview">
        <%= link_to "#" do %>
          <i class="fa fa-folder"></i>
          <span>Examples</span>
          <i class="fa fa-angle-left pull-right"></i>
        <% end %>
        <ul class="treeview-menu">
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-circle-o"></i> Invoice
            <% end %>
          </li>
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-circle-o"></i> Profile
            <% end %>
          </li>
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-circle-o"></i> Login
            <% end %>
          </li>
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-circle-o"></i> Register
            <% end %>
          </li>
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-circle-o"></i> Lockscreen
            <% end %>
          </li>
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-circle-o"></i> 404 Error
            <% end %>
          </li>
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-circle-o"></i> 500 Error
            <% end %>
          </li>
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-circle-o"></i> Blank Page
            <% end %>
          </li>
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-circle-o"></i> Pace Page
            <% end %>
          </li>
        </ul>
      </li>
      <li class="treeview">
        <%= link_to "#" do %>
          <i class="fa fa-share"></i>
          <span>Multilevel</span>
          <i class="fa fa-angle-left pull-right"></i>
        <% end %>
        <ul class="treeview-menu">
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-circle-o"></i> Level One
            <% end %>
          </li>
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-circle-o"></i> Level One
              <i class="fa fa-angle-left pull-right"></i>
            <% end %>
            <ul class="treeview-menu">
              <li>
                <%= link_to "#" do %>
                  <i class="fa fa-circle-o"></i> Level Two
                <% end %>
              </li>
              <li>
                <%= link_to "#" do %>
                  <i class="fa fa-circle-o"></i> Level Two
                  <i class="fa fa-angle-left pull-right"></i>
                <% end %>
                <ul class="treeview-menu">
                  <li>
                    <%= link_to "#" do %>
                      <i class="fa fa-circle-o"></i> Level Three
                    <% end %>
                  </li>
                  <li>
                    <%= link_to "#" do %>
                      <i class="fa fa-circle-o"></i> Level Three
                    <% end %>
                  </li>
                </ul>
              </li>
            </ul>
          </li>
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-circle-o"></i> Level One
            <% end %>
          </li>
        </ul>
      </li>
      <li>
        <%= link_to "#" do %>
          <i class="fa fa-book"></i>
          <span>Documentation</span>
        <% end %>
      </li>
      <li class="header">LABELS</li>
      <li>
        <%= link_to "#" do %>
          <i class="fa fa-circle-o text-red"></i>
          <span>Important</span>
        <% end %>
      </li>
      <li>
        <%= link_to "#" do %>
          <i class="fa fa-circle-o text-yellow"></i>
          <span>Warning</span>
        <% end %>
      </li>
      <li>
        <%= link_to "#" do %>
          <i class="fa fa-circle-o text-aqua"></i>
          <span>Information</span>
        <% end %>
      </li>
    </ul>
  </section>
</aside>

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> VINACOOK | Dashboard</title>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <%= stylesheet_link_tag "admin/application", media: "all", "data-turbolinks-track": "reload" %>
</head>
<body class="hold-transition skin-blue sidebar-mini">
  <div class="wrapper">
    <%= render "layouts/admin/header" %>
    <%= render "layouts/admin/sidebar" %>
    <div class="content-wrapper">
      <div class="messager">
        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
      </div>
      <%= yield %>
    </div>
    <%= render "layouts/admin/footer" %>
  </div>
</body>
<%= javascript_include_tag "admin/application", "data-turbolinks-track": "reload" %>
</html>

app/views/layouts/admin/application1.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> VINACOOK | Dashboard</title>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <%= stylesheet_link_tag "admin/application", media: "all", "data-turbolinks-track": "reload" %>
</head>
<body class="hold-transition login-page">
  <div class="wrapper">
    <div class="content">
      <div class="messager">
        <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
      </div>
      <%= yield %>
    </div>
  </div>
</body>
<%= javascript_include_tag "admin/application", "data-turbolinks-track": "reload" %>
</html>