config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/logout", to: "sessions#destroy"

  resources :carts, only: [:index, :destroy]
  resources :reviews, except: :update
  resources :product_orders
  resources :products
  resources :users
  resources :account_activations, only: :edit
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :login_checkouts
  resource :checkouts
  resource :orders, only: [:new, :update]
  resource :address, only: [:create, :update]
  resource :searchs

  namespace :admin do
    get "/login", to: "login#new"
    post "/login", to: "login#create"
    delete "/logout", to: "login#destroy"
    root "dashboard#index"
    get "dashboard/index"
    resources :products
    resources :categories
    resources :users
  end

end

app/controllers/checkouts_controller.rb
class CheckoutsController < ApplicationController
  before_action :check_address, only: [:show, :destroy]
  before_action :check_address_review, only: [:new, :create]
  before_action :check_address_review_exist, only: [:edit, :update]
  before_action :checkout_order

  def new
    @address = Address.new
  end

  def show; end

  def create
    @address = Address.new
    if current_user.present?
      unless params[:address][:email].empty? || params[:address][:phone].empty? ||
        params[:address][:address].empty? || params[:address][:city].empty?
        @order_address = current_user.addresses.build checkout_params
      else
        flash[:warning] = "email, phone, address, city can't be blank!"
        redirect_to new_checkouts_path and return
      end
      @order_address.save ? (redirect_to new_checkouts_path) : (redirect_to new_checkouts_path and return)
    else
      unless params[:address][:email].empty? || params[:address][:phone].empty? ||
        params[:address][:address].empty? || params[:address][:city].empty?
        session[:address] = checkout_params
        redirect_to new_checkouts_path
      else
        flash[:warning] = "email, phone, address, city can't be blank!"
        redirect_to new_checkouts_path
      end
    end
  end

  def edit; end

  def update
    unless params[:email].empty? || params[:phone].empty? || params[:address].empty? || params[:city].empty?
      current_user.present? ? (current_user.addresses.first.update address_params) : nil
      session[:address_review] = address_params
      redirect_to checkouts_path
    else
      redirect_to edit_checkouts_path
      flash[:warning] = "email, phone, address, city can't be blank!"
    end
  end

  private

  def checkout_params
    params.require(:address).permit :name, :email, :address, :city, :country,
    :phone
  end

  def address_params
    params.permit :name, :email, :address, :city, :country, :phone
  end

  def check_address
    return if session[:address_review].present?
    redirect_to new_login_checkout_path
  end

end

app/views/checkouts/_over_review.html.erb
<div class="order-review-wrapper">
  <div class="order-review">
    <div class="table-responsive">
      <table class="table">
        <thead>
          <tr>
            <th class="width-1">Product Name</th>
            <th class="width-2">Price</th>
            <th class="width-3">Qty</th>
            <th class="width-4">Subtotal</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <div class="o-pro-dec">
                <p>Fusce aliquam</p>
              </div>
            </td>
            <td>
              <div class="o-pro-price">
                <p>$236.00</p>
              </div>
            </td>
            <td>
              <div class="o-pro-qty">
                <p>2</p>
              </div>
            </td>
            <td>
              <div class="o-pro-subtotal">
                <p>$236.00</p>
              </div>
            </td>
          </tr>
          <tr>
            <td>
              <div class="o-pro-dec">
                <p>Primis in faucibus</p>
              </div>
            </td>
            <td>
              <div class="o-pro-price">
                <p>$265.00</p>
              </div>
            </td>
            <td>
              <div class="o-pro-qty">
                <p>3</p>
              </div>
            </td>
            <td>
              <div class="o-pro-subtotal">
                <p>$265.00</p>
              </div>
            </td>
          </tr>
          <tr>
            <td>
              <div class="o-pro-dec">
                <p>Etiam gravida</p>
              </div>
            </td>
            <td>
              <div class="o-pro-price">
                <p>$363.00</p>
              </div>
            </td>
            <td>
              <div class="o-pro-qty">
                <p>2</p>
              </div>
            </td>
            <td>
              <div class="o-pro-subtotal">
                <p>$363.00</p>
              </div>
            </td>
          </tr>
          <tr>
            <td>
              <div class="o-pro-dec">
                <p>Quisque in arcu</p>
              </div>
            </td>
            <td>
              <div class="o-pro-price">
                <p>$328.00</p>
              </div>
            </td>
            <td>
              <div class="o-pro-qty">
                <p>2</p>
              </div>
            </td>
            <td>
              <div class="o-pro-subtotal">
                <p>$328.00</p>
              </div>
            </td>
          </tr>
        </tbody>
        <tfoot>
          <tr>
            <td colspan="3">Subtotal </td>
            <td colspan="1">$4,001.00</td>
          </tr>
          <tr class="tr-f">
            <td colspan="3">Shipping & Handling (Flat Rate - Fixed</td>
            <td colspan="1">$45.00</td>
          </tr>
          <tr>
            <td colspan="3">Grand Total</td>
            <td colspan="1">$4,722.00</td>
          </tr>
        </tfoot>
      </table>
    </div>
    <div class="billing-back-btn">
      <span>
        Forgot an Item?
        <a href="#"> Edit Your Cart.</a>

      </span>
      <div class="billing-btn">
        <button type="submit">Continue</button>
      </div>
    </div>
  </div>
</div>

app/views/checkouts/_shipping_address.html.erb
<div class="shipping-information-wrapper">
  <div class="shipping-info-2">
    <span>HasTech</span>
    <span>Bonosrie</span>
    <span>D - Block</span>
    <span>Dkaka, 1201</span>
    <span>Bangladesh</span>
    <span>T: +8800 879 9876 </span>
  </div>
  <div class="edit-address">
    <a href="#">Edit Address</a>
  </div>
  <div class="billing-select">
    <select class="email s-email s-wid">
      <option>Select Your Address</option>
      <option>Add New Address</option>
      <option>Dkaka, 1201, Bangladesh</option>
    </select>
  </div>
  <div class="billing-back-btn">
    <div class="billing-btn">
      <button type="submit">Continue</button>
    </div>
  </div>
</div>

app/views/checkouts/edit.html.erb
<div class="row">
  <div class="col-lg-10 offset-1">
    <div class="billing-information-wrapper">
      <%= form_tag(checkouts_path, method: :patch) do %>
        <div class="row">
          <div class="col-lg-6 col-md-6">
            <div class="billing-info">
              <%= label_tag :name, "Name" %>
              <%= text_field_tag :name, session[:address_review]["name"] %>
            </div>
          </div>
          <div class="col-lg-6 col-md-6">
            <div class="billing-info">
              <%= label_tag :email, "Email" %>
              <%= email_field_tag :email, session[:address_review]["email"] %>
            </div>
          </div>
          <div class="col-lg-6 col-md-6">
            <div class="billing-info">
              <%= label_tag :address, "Address" %>
              <%= text_field_tag :address, session[:address_review]["address"] %>
            </div>
          </div>
          <div class="col-lg-6 col-md-6">
            <div class="billing-info">
              <%= label_tag :city, "City" %>
              <%= text_field_tag :city, session[:address_review]["city"] %>
            </div>
          </div>
          <div class="col-lg-6 col-md-6">
            <div class="billing-info">
              <%= label_tag :country, "Country" %>
              <%= text_field_tag :country, session[:address_review]["country"] %>
            </div>
          </div>
          <div class="col-lg-6 col-md-6">
            <div class="billing-info">
              <%= label_tag :phone, "Phone" %>
              <%= text_field_tag :phone, session[:address_review]["phone"] %>
            </div>
          </div>
          <div class="button-box">
            <%= button_tag "DONE", id:"checkout-next3" %>
            <%= link_to checkouts_path do %>
              <button type="submit" id="checkout-back1" >Back</button>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/checkouts/index.html.erb
<div class="order-review-wrapper">
  <div class="order-review">
    <div class="table-responsive">
      <table class="table">
        <thead>
          <tr>
            <th class="width-1">Product Name</th>
            <th class="width-2">Price</th>
            <th class="width-3">Qty</th>
            <th class="width-4">Subtotal</th>
          </tr>
        </thead>
        <tbody>
          <% current_order.product_orders.each do |product_order| %>
            <tr>
              <td>
                <div class="o-pro-dec">
                  <p><%= product_order.product.name %></p>
                </div>
              </td>
              <td>
                <div class="o-pro-price">
                  <p>$<%= product_order.product.price  %></p>
                </div>
              </td>
              <td>
                <div class="o-pro-qty">
                  <p><%= product_order.quantity %></p>
                </div>
              </td>
              <td>
                <div class="o-pro-subtotal">
                  <p>$ <%= product_order.product.price*product_order.quantity %></p>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
        <tfoot>
          <tr>
            <td colspan="1" id="addreview1">Name: <%= session[:address_review]["name"] %></td>
            <td colspan="2">Subtotal </td>
            <td colspan="1">$<%= current_order.subtotal %></td>
          </tr>
          <tr class="tr-f">
            <td colspan="1" id="addreview2">Email: <%= session[:address_review]["email"] %> </td>
            <td colspan="2">Shipping & Handling (Flat Rate - Fixed</td>
            <td colspan="1">$45</td>
          </tr>
          <tr>
            <td colspan="1" id="addreview3">Address: <%= session[:address_review]["address"] %> </td>
            <td colspan="2">Grand Total</td>
            <td colspan="1">$<%= current_order.subtotal + 45 %></td>
          </tr>
          <tr>
            <td colspan="4" id="addreview4">City: <%= session[:address_review]["city"] %></td>
          </tr>
          <tr>
            <td colspan="4" id="addreview5">Country: <%= session[:address_review]["country"] %></td>
          </tr><tr>
            <td colspan="4" id="addreview6">Phone: <%= session[:address_review]["phone"] %></td>
          </tr>
        </tfoot>
      </table>
    </div>
    <div class="checkout-back-btn">
      <%= link_to new_checkout_path do %>
        <div class="checkout-btn">
          <button type="submit">Edit Address</button>
        </div>
      <% end %>
      <%= link_to carts_path do %>
        <div class="checkout-btn">
          <button type="submit">Edit Cart</button>
        </div>
      <% end %>
      <%= link_to orders_path, method: :patch do %>
        <div class="checkout-btn">
          <button type="submit">Complete</button>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/checkouts/new.html.erb
<div class="row">
  <div class="col-lg-10 offset-1">
    <div class="checkout-wrapper">
      <div id="faq" class="pan el-group">
        <div class="panel panel-default">
          <div class="panel-body">
            <div class="billing-information-wrapper">
              <div class="row">
                <% if logged_in? %>
                  <% if current_user.addresses.present? %>
                    <% current_user.addresses.each do |address| %>
                      <div class="col-md-6 col-lg-6">
                        <%= form_tag(address_path, method: :post) do %>
                          <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
                          <div class="single-ship">
                            <input type="radio" name="address" value="address" checked="">
                            <label id="default-address">Using this address</label>
                          </div>
                          <div class="shipping-info-2">
                            <span>Name: <span id="address-name"><%= address.name.
                              empty? ? current_user.name : address.name%></span>
                            </span>
                            <span>Email: <span id="address-email"><%= address.email || current_user.email %></span></span>
                            <span>Address: <span id="address-address"><%= address.address %></span></span>
                            <span>City: <span id="address-city"><%= address.city %></span></span>
                            <span>Country: <span id="address-country"><%= address.country %></span></span>
                            <span>Phone: <span id="address-phone"><%= address.phone %></span></span>
                            <div class="billing-back-btn">
                              <div class="billing-btn">
                                <%= button_tag "Select", id:"checkout-next1" %>
                              </div>
                              <%= link_to address_path(:address_id => address.id), method: :patch do %>
                                <div class="billing-btn">
                                    <button type="submit" id="checkout-next1">DELETE</button>
                                </div>
                              <% end %>
                            </div>
                          </div>
                        <% end %>
                      </div>
                    <% end %>
                  <% end %>
                <% else %>
                  <% if session[:address].present? %>
                    <div class="col-md-6 col-lg-6">
                      <%= form_tag(address_path, method: :post) do %>
                        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
                        <div class="single-ship">
                          <input type="radio" name="address" value="address" checked="">
                          <label id="default-address">Using this address</label>
                        </div>
                        <div class="shipping-info-2">
                          <span>Name: <span id="address-name-1"><%= session[:address]["name"] %></span></span>
                          <span>Email: <span id="address-email-1"><%= session[:address]["email"] %></span></span>
                          <span>Address: <span id="address-address-1"><%= session[:address]["address"] %></span></span>
                          <span>City: <span id="address-city-1"><%= session[:address]["city"] %></span></span>
                          <span>Country: <span id="address-country-1"><%= session[:address]["country"] %></span></span>
                          <span>Phone: <span id="address-phone-1"><%= session[:address]["phone"] %></span></span>
                          <div class="billing-back-btn">
                            <div class="billing-btn">
                              <%= button_tag "Select", id:"checkout-next2" %>
                            </div>
                          </div>
                        </div>
                      <% end %>
                    </div>
                  <% end %>
                <% end %>
              </div>
              <div class="single-ship">
                <input type="radio" name="address" value="address" checked="">
                <label id="add-new-address">Add new address</label>
              </div>
              <%= form_for @address, url: {controller: :checkouts, action: :create}, method: :post, remote: true do |f| %>
                <div class="row">
                  <div class="col-lg-6 col-md-6">
                    <div class="billing-info">
                      <%= f.label :name, "Name" %>
                      <%= f.text_field :name %>
                    </div>
                  </div>
                  <div class="col-lg-6 col-md-6">
                    <div class="billing-info">
                      <%= f.label :email, "Email" %>
                      <%= f.email_field :email %>
                    </div>
                  </div>
                  <div class="col-lg-6 col-md-6">
                    <div class="billing-info">
                      <%= f.label :address, "Address" %>
                      <%= f.text_field :address %>
                    </div>
                  </div>
                  <div class="col-lg-6 col-md-6">
                    <div class="billing-info">
                      <%= f.label :city, "City" %>
                      <%= f.text_field :city %>
                    </div>
                  </div>
                  <div class="col-lg-6 col-md-6">
                    <div class="billing-info">
                      <%= f.label :country, "Country" %>
                      <%= f.text_field :country %>
                    </div>
                  </div>
                  <div class="col-lg-6 col-md-6">
                    <div class="billing-info">
                      <%= f.label :phone, "Phone" %>
                      <%= f.text_field :phone %>
                    </div>
                  </div>
                  <div class="button-box">
                    <%= f.button "Add", id:"checkout-next3" %>
                    <%= link_to new_login_checkout_path do %>
                      <button type="submit" id="checkout-back1" >Back</button>
                    <% end %>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/checkouts/show.html.erb
<div class="order-review-wrapper">
  <div class="order-review">
    <div class="table-responsive">
      <table class="table">
        <thead>
          <tr>
            <th class="width-1">Product Name</th>
            <th class="width-2">Price</th>
            <th class="width-3">Qty</th>
            <th class="width-4">Subtotal</th>
          </tr>
        </thead>
        <tbody>
          <% current_order.product_orders.each do |product_order| %>
            <tr>
              <td>
                <div class="o-pro-dec">
                  <p><%= product_order.product.name %></p>
                </div>
              </td>
              <td>
                <div class="o-pro-price">
                  <p>$<%= product_order.product.price  %></p>
                </div>
              </td>
              <td>
                <div class="o-pro-qty">
                  <p><%= product_order.quantity %></p>
                </div>
              </td>
              <td>
                <div class="o-pro-subtotal">
                  <p>$ <%= product_order.product.price*product_order.quantity %></p>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
        <tfoot>
          <tr>
            <td colspan="1" id="addreview1">Name: <%= session[:address_review]["name"] %></td>
            <td colspan="2">Subtotal </td>
            <td colspan="1">$<%= current_order.subtotal %></td>
          </tr>
          <tr class="tr-f">
            <td colspan="1" id="addreview2">Email: <%= session[:address_review]["email"] %> </td>
            <td colspan="2">Shipping & Handling (Flat Rate - Fixed</td>
            <td colspan="1">$45</td>
          </tr>
          <tr>
            <td colspan="1" id="addreview3">Address: <%= session[:address_review]["address"] %> </td>
            <td colspan="2">Grand Total</td>
            <td colspan="1">$<%= current_order.subtotal + 45 %></td>
          </tr>
          <tr>
            <td colspan="4" id="addreview4">City: <%= session[:address_review]["city"] %></td>
          </tr>
          <tr>
            <td colspan="4" id="addreview5">Country: <%= session[:address_review]["country"] %></td>
          </tr><tr>
            <td colspan="4" id="addreview6">Phone: <%= session[:address_review]["phone"] %></td>
          </tr>
        </tfoot>
      </table>
    </div>
    <div class="checkout-back-btn">
      <%= link_to edit_checkouts_path do %>
        <div class="checkout-btn">
          <button type="submit">Edit Address</button>
        </div>
      <% end %>
      <%= link_to carts_path do %>
        <div class="checkout-btn">
          <button type="submit">Edit Cart</button>
        </div>
      <% end %>
      <%= link_to orders_path, method: :patch do %>
        <div class="checkout-btn">
          <button type="submit">Complete</button>
        </div>
      <% end %>
    </div>
  </div>
</div>