config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/logout", to: "sessions#destroy"

  resources :carts, only: [:index, :destroy]
  resources :reviews, except: :update
  resources :product_orders
  resources :products
  resources :users
  resources :account_activations, only: :edit
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :login_checkouts
  resource :checkouts
  resource :orders, only: [:new, :update]
  resource :address, only: [:create, :update]
  resource :searchs

  namespace :admin do
    get "/login", to: "login#new"
    post "/login", to: "login#create"
    delete "/logout", to: "login#destroy"
    root "dashboard#index"
    get "dashboard/index"
    resources :products
    resources :categories
    resources :users
  end

end

app/models/product.rb
class Product < ApplicationRecord
  has_many :product_orders, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :rates
  has_many :comments
  has_many :product_categories
  has_many :categories, through: :product_categories
  validates :price, presence: true
  validates :name, presence:true, uniqueness: true
  default_scope -> { order(created_at: :desc)}
  validates :price, presence: true, format: { with: /\A\d+(?:\.\d{2})?\z/ },
  numericality: { greater_than: 0, less_than: 1000000}
  validates :sale_price, presence: true, allow_blank: true, format: { with: /\A\d+(?:\.\d{2})?\z/ },
  numericality: { greater_than: 0, less_than: 1000000}
  mount_uploader :image, PictureUploader
  scope :best_product, -> {order sale_count: :desc}
  scope :search_name, -> (name) {where("name like ?", "%#{name}%")}
  scope :search_product_category, -> (category_id){joins(:product_categories).where("category_id = #{category_id}")}
  scope :search_product_name, -> (name, category_id){joins(:product_categories).where("category_id = #{category_id}").where("name like ?", "%#{name}%")}
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController
  before_action :load_product, except: [:index, :new, :create]
  def index
    @products = Product.all
    @products = @products.search_name params[:search_name] if params[:search_name].present?
    @categories_for_search = Category.pluck :name, :id
    @products = @products.search_product_category params[:category_id] if params[:category_id].present?
    @products = @products.paginate page: params[:page], per_page: 25
  end

  def new
    @product = Product.new
    @show_categories = Category.pluck :name, :id
  end

  def create
    @product = Product.new product_params
    if @product.save
      flash[:success] = "Thêm sản phẩm mới thành công"
      redirect_to admin_products_path
    else
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    if @product.update_attributes product_params
      flash[:success] = "Cập nhật thành công"
      redirect_to admin_products_path
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    flash[:success] = "Đã xóa hãng thành công"
    redirect_to admin_products_path
  end

  private
  def product_params
    params.require(:product).permit :name, :price, :image, :description,
      :sale_price, :status, category_ids: []
  end

  def load_product
    @product = Product.find_by id: params[:id]
    return if @product
    flash[:danger]="Sản phẩm không tồn tại"
    redirect_to admin_products_path
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
    if params[:search_name].present? && params[:category_id].present?
      @products = @products.search_product_name params[:search_name], params[:category_id]
      flash[:info] = "Không có sản phẩm nào được tìm thấy!" if @products.empty?
    elsif params[:search_name].present?
      @products = @products.search_name params[:search_name]
      flash[:info] = "Không có sản phẩm nào được tìm thấy!" if @products.empty?
    elsif params[:category_id].present?
      @products = @products.search_product_category params[:category_id]
      flash[:info] = "Không có sản phẩm nào được tìm thấy!" if @products.empty?
    else
     flash[:warning] = "Bạn phải điền tên sản phẩm hoặc chọn danh mục!"
     redirect_to root_url
    end
    @categories_for_search = Category.pluck :name, :id
    @products = @products.paginate page: params[:page], per_page: 10
    @product_order = current_order.product_orders.build
  end

  def show
    @product = Product.find_by id: params[:id]
    @best_products = Product.best_product.limit 4
    @categories = Category.limit 5
    @review = Review.new
    @avg_rate = @product.reviews.average(:rate)&.round(2) || 0
  end

end

app/views/admin/products/_form.html.erb
<%= form_for [:admin, @product] do |f| %>
  <%= render "shared/admin/error_messages", object: f.object %>
  <div class="box-body pad">
    <div class="form-group">
      <div class="form-content">
        <label class="col-md-2 control-label"> Tên sản phẩm:
          <span class="required">
            *
          </span>
        </label>
        <div class="col-md-10 mg-10">
          <%= f.text_field :name, class: "form-control" %>
        </div>
      </div>
      <div class="form-content">
        <label class="col-md-2 control-label"> Giá sản phẩm:
          <span class="required">
            *
          </span>
        </label>
        <div class="col-md-10 mg-10">
          <%= f.text_field :price, class: "form-control" %>
        </div>
      </div>
      <div class="form-content">
        <label class="col-md-2 control-label"> Hình ảnh sản phẩm:
          <span class="required">
            *
          </span>
        </label>
        <div class="col-md-10 mg-10">
          <%= f.file_field :image %>
        </div>
      </div>
      <div class="form-content">
        <label class="col-md-2 control-label"> Mô tả sản phẩm:
          <span class="required">
            *
          </span>
        </label>
        <div class="col-md-10 mg-10">
          <%= f.text_field :description, class: "form-control" %>
        </div>
      </div>
      <div class="form-content">
        <label class="col-md-2 control-label"> Giá khuyến mại:
          <span class="required">
            *
          </span>
        </label>
        <div class="col-md-10 mg-10">
          <%= f.text_field :sale_price, class: "form-control" %>
        </div>
      </div>
      <div class="form-content">
        <label class="col-md-2 control-label"> Trạng thái sản phẩm:
          <span class="required">
            *
          </span>
        </label>
        <div class="col-md-10 mg-10">
          <%= f.text_field :status, class: "form-control" %>
        </div>
      </div>
      <div class="form-content">
        <label class="col-md-2 control-label"> Danh mục sản phẩm:
          <span class="required">
            *
          </span>
        </label>
        <div class="col-md-10 mg-10">
          <%= f.collection_check_boxes :category_ids,
            Category.all, :id, :name do |category| %>
            <ul class="select-category">
              <li>
                <%= category.check_box %>
                <%= category.label %>
              </li>
            </ul>
          <% end %>
        </div>
      </div>
      <%= f.submit "Thêm mới", class: "btn btn-success" %>
    </div>
  </div>
<% end %>

app/views/admin/products/edit.html.erb
<% provide :title, "Chỉnh sửa thông tin" %>
  <section class="content-header">
    <h1>
      Chỉnh sửa sản phẩm
    </h1>
  </section>
  <section class="content">
    <div class="row">
      <div class="col-md-12">
        <div class="box">
          <div class="row">
            <div class="form-group">
              <%= form_for [:admin, @product] do |f| %>
                <div class="form-content">
                  <label class="col-md-2 control-label"><%= f.label :name, "Tên sản phẩm" %>
                    <span class="required">
                     *
                    </span>
                  </label>
                  <div class="col-md-10 mg-10">
                    <%= f.text_field :name, placeholder: "Nhập tên sản phẩm", class: "form-control" %>
                  </div>
                </div>
                <div class="form-content cleafix">
                  <label class="col-md-2 control-label"><%= f.label :price, "Giá sản phẩm" %>
                    <span class="required">
                     *
                    </span>
                  </label>
                  <div class="col-md-10 mg-10">
                    <%= f.text_field :price, placeholder: "Nhập giá", class: "form-control" %>
                  </div>
                </div>
                <div class="form-content cleafix">
                  <label class="col-md-2 control-label"><%= f.label :sale_price, "Giá khuyến mại" %>
                    <span class="required">
                     *
                    </span>
                  </label>
                  <div class="col-md-10 mg-10">
                    <%= f.text_field :sale_price, placeholder: "Nhập giá khuyến mại", class: "form-control" %>
                  </div>
                </div>
                <div class="form-content cleafix">
                  <label class="col-md-2 control-label"><%= f.label :description, "Mô tả sản phẩm" %>
                    <span class="required">
                     *
                    </span>
                  </label>
                  <div class="col-md-10 mg-10">
                    <%= f.text_field :description, placeholder: "Nhập mô tả sản phẩm", class: "form-control" %>
                  </div>
                </div>
                <div class="form-content">
                  <label class="col-md-2 control-label"> Danh mục sản phẩm:
                    <span class="required">
                      *
                    </span>
                  </label>
                  <div class="col-md-10 mg-10">
                    <%= f.collection_check_boxes :category_ids,
                      Category.all, :id, :name do |category| %>
                      <ul class="select-category">
                        <li>
                          <%= category.check_box %>
                          <%= category.label %>
                        </li>
                      </ul>
                    <% end %>
                  </div>
                </div>
                <div class="form-content">
                  <label class="col-md-2 control-label"> Hình ảnh sản phẩm:
                    <span class="required">
                      *
                    </span>
                  </label>
                  <div class="col-md-10 mg-10">
                    <%= image_tag @product.image, class: "image_product_admin" %>
                    <%= f.file_field :image %>
                  </div>
                </div>
                <div class="form-content cleafix">
                  <label class="col-md-2 control-label"><%= f.label :status, "Trạng thái sản phẩm" %>
                    <span class="required">
                     *
                    </span>
                  </label>
                  <div class="col-md-10 mg-10">
                    <%= f.text_field :status, placeholder: "Trạng thái sản phẩm", class: "form-control" %>
                  </div>
                </div>
                <div class="form-content">
                  <div class="col-md-12">
                    <%= f.submit "Cập nhật", class: "btn btn-primary" %>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

app/views/admin/products/index.html.erb
<section class="content-header">
  <h1 class="admin-title">
    Tất cả sản phẩm
  </h1>
  <div class="bnt-new">
    <%= link_to "create product", new_admin_product_path %>
  </div>
</section>
<section class="content">
  <div class="row">
    <div class="search-form col-md-12">
      <div class="category-product">
        <%= form_tag admin_products_path, method: :get do %>
          <%= text_field_tag "search_name", params[:search_name], placeholder:
          "Enter products name" %>
          <%= select_tag :category_id, options_for_select(@categories_for_search), include_blank: true %>
          <%= submit_tag "Search!" %>
        <% end %>
      </div>
    </div>
    <div class="col-md-12">
      <div class="box">
        <table>
          <thead>
            <tr>
              <th>ID</th>
              <th>Tên sản phẩm</th>
              <th>Danh mục sản phẩm</th>
              <th>Gía</th>
              <th>Gía khuyến mại</th>
              <th>Hình ảnh sản phẩm</th>
              <th>Trạng thái</th>
              <th>Chi tiết</th>
              <th>Chỉnh sửa</th>
              <th>Xóa</th>
            </tr>
          </thead>
          <tbody>
            <% @products.each do |product| %>
              <tr>
                <td><%= product.id %></td>
                <td><%= product.name %></td>
                <td>
                  <% product.categories.each do |category| %>
                   <%= "#{category.name}, " %>
                  <% end %>
                </td>
                <td><%= product.price %></td>
                <td><%= product.sale_price %></td>
                <td><%= image_tag product.image.url || "product/default.jpg", class: "image_product_admin" %></td>
                <td><%= product.status %></td>
                <td><%= link_to "Hiển thị", admin_product_path(product) %></td>
                <td><%= link_to "Chỉnh sửa", edit_admin_product_path(product) %></td>
                <td><%= link_to "Xóa", [:admin, product],
                  data: { confirm: "Are you sure?" }, method: :delete %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= will_paginate @products %>
      </div>
    </div>
  </div>
</section>

app/views/admin/products/new.html.erb
<section class="content-header">
  <h1>
    Thêm mới sản phẩm
  </h1>
</section>
<section class="content">
  <div class="row">
    <div class="col-md-12">
      <div class="box">
        <%= render "form" %>
      </div>
    </div>
  </div>
</section>

app/views/admin/products/show.html.erb
<section class="content-header">
  <h1>
    Chi tiết sản phẩm
  </h1>
</section>
<section class="content">
  <div class="row">
    <div class="col-md-12">
      <div class="box">
        <table>
          <tr>
            <th>Tên sản phẩm</th>
            <th>Mô tả sản phẩm</th>
             <th>Gía sản phẩm</th>
            <th>Gía khuyến mại</th>
            <th>Hình ảnh sản phẩm</th>
            <th>Trạng thái</th>
            <th>Chỉnh sửa</th>
          </tr>
          <td><%= @product.name %></td>
          <td><%= @product.description %></td>
          <td><%= @product.price %></td>
          <td><%= @product.sale_price %></td>
          <td><%= image_tag @product.image, class: "image_product_admin" %></td>
          <td><%= @product.status %></td>
          <td><%= link_to "Chỉnh sửa", edit_admin_product_path %></td>
        </table>
      </div>
    </div>
  </div>
</section>