config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/logout", to: "sessions#destroy"

  resources :carts, only: [:index, :destroy]
  resources :reviews, except: :update
  resources :product_orders
  resources :products
  resources :users
  resources :account_activations, only: :edit
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :login_checkouts
  resource :checkouts
  resource :orders, only: [:new, :update]
  resource :address, only: [:create, :update]
  resource :searchs

  namespace :admin do
    get "/login", to: "login#new"
    post "/login", to: "login#create"
    delete "/logout", to: "login#destroy"
    root "dashboard#index"
    get "dashboard/index"
    resources :products
    resources :categories
    resources :users
  end

end

app/controllers/login_checkouts_controller.rb
class LoginCheckoutsController < ApplicationController
  before_action :check_login, only: [:new, :create]
  before_action :checkout_order, only: [:new, :create]
  before_action :check_address_review, only: [:new, :create]

  def new
    @user = User.new
    @user.addresses.build
  end

  def create
    user = User.find_by email: params[:session][:email]
    if user && user.authenticate(params[:session][:password])
      if user.activated?
        log_in user
        redirect_to new_checkouts_path
      else
        message  = "Account not activated. "
        message += "Check your email for the activation link."
        flash[:warning] = message
        redirect_to root_url
      end
    else
      flash[:danger] = "Invalid email/password combination"
      redirect_to new_login_checkout_path
    end
  end

  private

  def check_login
    return unless logged_in?
    redirect_to new_checkouts_path
  end

end

app/views/login_checkouts/new.html.erb
<div class="breadcrumb-area gray-bg">
  <div class="container">
    <div class="breadcrumb-content">
      <ul>
        <li><a href="index.html">Home</a></li>
        <li class="active"> Checkout </li>
      </ul>
    </div>
  </div>
</div>
<!-- checkout-area start -->
<div class="checkout-area pb-80 pt-100">
  <div class="container">
    <div class="row">
      <div class="col-lg-10 offset-1">
        <div class="checkout-wrapper">
          <div id="faq" class="pan el-group">
            <div class="panel panel-default">
                <div class="panel-body">
                  <div class="row" id="panel-body-row">
                    <div class="col-lg-6">
                      <div class="checkout-login">
                        <div class="title-wrap">
                          <h4 class="cart-bottom-title section-bg-white">REGISTER</h4>
                        </div>
                        <p>Already have an account? </p>
                        <span>Please register below:</span>
                        <%= form_for @user, url: {controller: :users, action: :create}, method: :post do |f|%>
                          <div class="login-form">
                            <%= f.label :name, "Name*" %>
                            <%= f.text_field :name %>
                          </div>
                          <div class="login-form">
                            <%= f.label :email, "Email Address*" %>
                            <%= f.email_field :email %>
                          </div>
                          <div class="login-form">
                            <%= f.label :password, "Password*" %>
                            <%= f.password_field :password %>
                          </div>
                          <%= f.fields_for :addresses do |ff| %>
                            <div class="login-form">
                              <%= f.label :password, "Address*" %>
                              <%= ff.text_field :address %>
                            </div>
                            <div class="login-form">
                              <%= f.label :password, "City*" %>
                              <%= ff.text_field :city %>
                            </div>
                            <div class="login-form">
                              <%= f.label :password, "Phone*" %>
                              <%= ff.text_field :phone %>
                            </div>
                          <% end %>
                          <div class="login-forget">
                            <p>* Require Fields</p>
                          </div>
                          <div class="button-box">
                            <%= f.button "Submit", id: "submit-checkout" %>
                            <%= link_to new_checkouts_path do %>
                              <button type="submit">As Guest</button>
                            <% end %>
                          </div>
                        <% end %>
                      </div>
                    </div>
                    <div class="col-lg-6">
                      <div class="checkout-login">
                        <div class="title-wrap">
                          <h4 class="cart-bottom-title section-bg-white">LOGIN</h4>
                        </div>
                        <p>Already have an account? </p>
                        <span>Please log in below:</span>
                        <%= form_for :session, url: {controller: :login_checkouts, action: :create}, method: :post do |f|%>
                          <div class="login-form">
                            <%= f.label :email, "Email Address*" %>
                            <%= f.email_field :email %>
                          </div>
                          <div class="login-form">
                            <%= f.label :password, "Password*" %>
                            <%= f.password_field :password %>
                          </div>
                          <div class="login-forget">
                            <%= link_to "Forgot your password?", new_password_reset_path %>
                            <p>* Require Fields</p>
                          </div>
                          <div class="button-box">
                            <%= f.button "Login", id: "login-checkout" %>
                          </div>
                        <% end %>
                      </div>
                    </div>
                  </div>
                </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>